### PR TITLE
support GetFPCHeapStatus

### PR DESCRIPTION
**Pull request by red-prig**

### CODE REVIEW

**Review by maximmasiutin — APPROVED** [review]

**Comment by maximmasiutin** [comment]
Thank you very much! I have applied the pull request. However, I have made a subsequent commit with alignment changes, in  case and spaces only. The code was not formatted according to the object pascal style guide introduced by Borland.

**Comment by maximmasiutin** [comment]
You have made a comment "prevents potential UB on FPC". How does this "UB" abbreviation expanded? Can you please clarify?

**Comment by red-prig** [comment]
@maximmasiutin in the case of uninitialized variables in some versions of the FPC, I met with the fact that it may contain random data (undefined behavior), the problem is aggravated by the fact that the TMemoryManager record contains more variables than the delphi version

**Comment by maximmasiutin** [comment]
@red-prig - Thank you, I have replaced this abbreviation with full words

**Comment by red-prig** [comment]
@maximmasiutin ok

**Pull request merged**
