### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by red-prig**
I propose to use a system ThreadSwitch, add GetFPCHeapStatus support and fix bugs for Linux compilation

### CODE REVIEW

**Comment by ValtsS** [comment]
System.ThreadSwitch is not present in older versions of Delphi.
Same issues with the InitCriticalSection/... stuff. So no.

**Comment by red-prig** [comment]
isn't this fork focused on FPS compatibility or am I wrong?

**Comment by maximmasiutin** [comment]
Thank you for sharing the code that will improve Linux compatibility. Unfortunately, I don't have a Linux machine at the moment. I did only test with Delphi and with FreePascal under Windows.

The main problem is that there are many routines written in Assembly that do not honor Linux register calling convention: they do only have Windows-version, while other routines have ifdefs that properly work under Linux.

**Comment by maximmasiutin** [comment]
@red-prig can you please check whether the new update of FastMM4-AVX (Version 1.04) compiles and runs properly under Linux? You have observed that previous version (1.03) crashed under Linux in GetCPUID and provided a fix, related to correct use of registers that hold parameters? In 1.04, I made explicit order of parameters for GetCPUID to avoid calling convention ambiguity that could lead to incorrect use of registers and finally crashes, i.e. under Linux as you have reported. Can you check that? Do we still need other fixes from your proposal, i.e. a conditional define for critical sections or System.ThreadSwitch which is a Linux alternative to Windows SwitchToThread() API call?

@ValtsS can you check 1.04 under the oldest version of Delphi?

**Comment by ValtsS** [comment]
@maximmasiutin it at very least builds OK and the simplest application runs with it.

**Comment by maximmasiutin** [comment]
@ValtsS - thank you very much for your prompt reply.

**Comment by red-prig** [comment]
sorry i don't check emails, in general there were three problems with GetCPUID, ThreadSwitch and critical section function naming (system.*)

**Comment by ezurschmiede** [comment]
Guten Tag,

vielen Dank für Ihre E-Mail.

Ich bin bis am 19.10.2020 in den Herbstferien. Die eingehenden E-Mails werden während dieser Zeit nicht bearbeitet.

Wenn es kein persönliches Anliegen ist, wenden Sie sich doch bitte an support@delight.ch oder an info@delight.ch

Schöne Grüsse
Elias Zurschmiede

delight software gmbh

**Comment by maximmasiutin** [comment]
@red-prig I have just made a commit today to make it compile by FreePascal for Linux. Could you please check whether it runs properly?

**Comment by ValtsS** [comment]
@maximmasiutin good news is that it still works with D5 👍

**Comment by red-prig** [comment]
@maximmasiutin Well, I tested (Linux x64) with a single threaded application, everything is fine.
  In a multithreaded application, it crashed at the end of the thread (I do not claim that this is your mistake) on the functions: MOVE216AVX1 and MOVE216AVX2 and without AVX, everything is fine (maybe I went outside the array boundary somewhere).
But now there are compilation errors for FPC for windows, lines:

`{$ifndef POSIX}
  FSwitchToThread := GetProcAddress(GetModuleHandle(Kernel32), 'SwitchToThread');
{$endif} `

and

`        {$ifndef POSIX}
        if Assigned(FSwitchToThread) then
        {$endif}     `

**Comment by red-prig** [comment]
PPS: Windows multithreaded application worked is fine.

**Comment by maximmasiutin** [comment]
@red-prig Thank you, I have made (committed) a change and now it compiles under FreePascal for Windows.

However, I'm worried why it crashes in a 64-bit application for Linux. Do you mean that it stops crashing if you compile it with "DisableAVX" conditional define?

**Comment by red-prig** [comment]
@maximmasiutin yes it crashed AV at the end of the thread, in multithreaded application.
With DisableAVX work normaly, and the same program on win64 works normaly with in AVX.

¯\_(ツ)_/¯

**Comment by hafedh-trimeche** [comment]
Hello,

Please find Hints & Error:

```
[dcc32 Hint] FastMM4.pas(6855): H2077 Value assigned to 'LLockLargeBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(6823): H2077 Value assigned to 'LLockLargeBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(6996): H2077 Value assigned to 'LLargeBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(7684): H2077 Value assigned to 'LSmallBlockWithoutLock' never used
[dcc32 Hint] FastMM4.pas(7646): H2077 Value assigned to 'LMediumBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(7619): H2077 Value assigned to 'LSmallBlockWithoutLock' never used
[dcc32 Hint] FastMM4.pas(7610): H2077 Value assigned to 'LMediumBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(7889): H2077 Value assigned to 'LMediumBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(7794): H2077 Value assigned to 'LMediumBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(7317): H2077 Value assigned to 'LMediumBlocksLocked' never used
[dcc32 Hint] FastMM4.pas(9240): H2077 Value assigned to 'LMediumBlocksLocked' never used

```
Error generated when **SmallBlocksLockedCriticalSection** is defined. 

[dcc32 Error] FastMM4.pas(9436): E2033 Types of actual and formal var parameters must be identical

```
{$else SmallBlocksLockedCriticalSection}

      while not (AcquireLockByte(@(LPSmallBlockType.SmallBlockTypeLocked))) do
      begin
{$ifdef UseReleaseStack}
        LPReleaseStack := @LPSmallBlockType.ReleaseStack[GetStackSlot];
        if (not LPReleaseStack^.IsFull) and LPReleaseStack^.Push(APointer) then
        begin
          {Block will be released later.}
          Result := 0;
          Exit;
        end;
{$endif}
{$ifdef LogLockContention}
        LDidSleep := True;
{$endif}
{$ifdef NeverSleepOnThreadContention}
  {$ifdef UseSwitchToThread}
        SwitchToThreadIfSupported;
  {$endif}
{$else}
        Sleep(InitialSleepTime);
        if AcquireLockByte(@(LPSmallBlockType.SmallBlockTypeLocked)) then
          Break;
        Sleep(AdditionalSleepTime);
{$endif}
      end;

{$endif SmallBlocksLockedCriticalSection}

```

**Comment by maximmasiutin** [comment]
@hafedh-trimeche Thank you! I have made a fix and a commit. Could you please try again now?

**Comment by hafedh-trimeche** [comment]
Source updated but error persisted.

`{.$define SmallBlocksLockedCriticalSection}
`
Regards.

**Comment by red-prig** [comment]
@maximmasiutin yes it worked, thanks!

Well, what about supporting a specific GetFPCHeapStatus? For example, I use it to analyze memory usage statistics.

**Comment by maximmasiutin** [comment]
@red-prig I have just made a commit. Can you please check. Move216AVX1 and Move216AVX2 Linux implementation had invalid opcodes (from the Windows implementation). I have fixed the opcodes and re-enabled these functions (they were disabled under Linux by a conditional define). 

I will add the GetFPCHeapStatus from your pull request then.

**Comment by red-prig** [comment]
@maximmasiutin nop its crash.

I have fixed a minimal example of a bug:

`program bugs;

uses
 cthreads,
 FastMM4;

var
 pt:Pointer;

begin
 pt:=Getmem(200);
 ReAllocMem(pt,272);
end.   `

The bugs project has thrown an exception class 'External: SIGSEGV'.

In the file '../hashtest/FastMM4/FastMM4.pas' on line 4169:
add rsi, 60h

**Comment by red-prig** [comment]
hmm but strange, assembler view points to a line:

`0000000000427D4D c5fd6f49c0               vmovdqa -0x40(%rcx),%ymm1`

**Comment by maximmasiutin** [comment]
@red-prig 
Thank you! I have found two more invalid opcodes. Committed a fix. Please try again.

**Comment by maximmasiutin** [comment]
Thank you for sharing the code that reproduced this bug. I run it under Linux, with Lazarus IDE, and was able to put the breakpoint in the Move216AVX2, and saw that it was now OK, after the last commit.

**Comment by maximmasiutin** [comment]
Please confirm that it is now OK.

**Comment by red-prig** [comment]
@maximmasiutin yes it worked ))

**Comment by red-prig** [comment]
@maximmasiutin I found an interesting feature if I try to compile on the beta version of FPС 3.3.1, then on line 16481 of the FastMM.pas file, instead of the constant 300, 448 is needed (win64 in any case)

```
  {$ifdef FPC}
  if HeapTotalAllocated > 448 then // allow up to 300 bytes to FreePascal until we figure out how to install our heap manager properly BEFORE any call
  {$else}
```

**Comment by maximmasiutin** [comment]
@red-prig I have researched this issue. Increasing the value, e.g. to 448, would not help, because FreePascal allocates memory from the initialization section of the system.pp unit, including for the command line buffers. 

I have submitted a bug report at https://bugs.freepascal.org/view.php?id=38391

Please login and support the bug report.

In the meanwhile, we can comment this check altogether for FreePascal, but if the FastMM would not be the first unit, we will not notice troubles.

**Comment by maximmasiutin** [comment]
I have updated the source code and removed the check altogether, because with long command lines 448 bytes would not be enough. Should you notice further issues, please submit new bug report or new pull requests rather than adding to this one, i.e. https://github.com/maximmasiutin/FastMM4-AVX/pull/13

**Comment by red-prig** [comment]
ok understood

**Comment by maximmasiutin** [comment]
Hello Pavel,

Wednesday, December 2, 2020, 8:13:52 PM, you wrote:

> @maximmasiutin I found an interesting feature if I try to compile on the
> beta version of FPС 3.3.1, then on line 16481 of the FastMM.pas file,
> instead of the constant 300, 448 is needed (win64 in any case)

Could you please test the latest version of FastMM4-AVX? I made lots of changes for FreePascal during the past two weeks. By the way, don't you know how to make FreePascal correctly adjust relative +RIP (instruction pointer) addresses in inlined assembly code for 64-bit Windows? It only makes such offsets correctly for 32-bit. Therefore under 64-bit Windows, I cannot use AsmMode conditional define that reads variables from the Data segment. I have to pass the addresses of these arguments as a function parameter. Maybe just put all the data from the data segment to a single Record and pass the pointer to this record to the assembly function as an argument, so the FreePascal would not need to correct the offsets?





--

**Comment by red-prig** [comment]
Well, I'll test it a little later. As for the offsets in x64, if I remember correctly and if I understood you correctly, there are no processor assembly instructions and therefore Pascal cannot convert them correctly. Also, can you use a uniform method of passing parameters (ABI)? Not so long ago I myself found out that Free Pascal supports:
```
        DefProcCallName : array[tproccalloption] of string[16] = ('',
         'CDECL',
         'CPPDECL',
         'FAR16',
         'OLDFPCCALL',
         '', { internproc }
         '', { syscall }
         'PASCAL',
         'REGISTER',
         'SAFECALL',
         'STDCALL',
         'SOFTFLOAT',
         'MWPASCAL',
         'INTERRUPT',
         'HARDFLOAT',
         'SYSV_ABI_DEFAULT',
         'SYSV_ABI_CDECL',
         'MS_ABI_DEFAULT',
         'MS_ABI_CDECL',
         'VECTORCALL'
        );
```
I can't tell you which version it came from, but it works in the stable version (3.2.0), as it is not reflected in the documentation. 
Thus, you can use MS ABI (MS_ABI_DEFAULT) in Linux and vice versa (SYSV_ABI_DEFAULT).

**Comment by red-prig** [comment]
@maximmasiutin And what about FPС 3.3.1, can it still use the inverse calculation of the memory size? these are not exact numbers, but it seems to work. 
```
{$if FPC_FULLVERSION> 30300}
//well, I suggest so far this is a workground
Function CalcArgvAlloc:NativeUInt;
var
 pc:ppchar;
begin
 Result:=System.MemSize(CmdLine);
 pc:=argv;
 if pc<>nil then
 begin
  Result:=Result+System.MemSize(pc)*3; //sum to near the size of argvw
  While (pc^<>nil) do
  begin
   Result:=Result+System.MemSize(pc^)*3; //sum to near the size of argvw^
   Inc(pc);
  end;
 end;
end; 
{$endif}

//-------------------- in CheckCanInstallMemoryManager

{$if FPC_FULLVERSION> 30300}
HeapTotalAllocated:=HeapTotalAllocated-CalcArgvAlloc;
{$endif}

```

**Comment by red-prig** [comment]
@maximmasiutin Well new version is crashed. (Win64 Tested) Example: 
```
program bugs;

uses
 {$IFDEF Unix}
 cthreads,
 {$ENDIF}
 FastMM4;

var
 pt:Pointer;

begin
 pt:=Getmem(56);
 ReAllocMem(pt,72);
end. 
```
Param:

> -dDisableMemoryLeakReporting
-dIgnoreMemoryAllocatedBefore

CallStack:
> #0 MOVE56AVX2(56) at :0
#1 FASTREALLOCMEM(0x2af8cf0, 72) at FastMM4\FastMM4.pas:12519
#2 SYSTEM_$$_REALLOCMEM$POINTER$QWORD$$POINTER at :0
#3 main at bugs.lpr:14

**Comment by maximmasiutin** [comment]
Thank you, I have just fixed it. Could you please check!?

**Comment by red-prig** [comment]
@maximmasiutin I did not find any more problems under Windows, but I also found a compilation problem for Linux, with a certain combination of flags, a compilation error: 

> procedure AcquireSpinLockMediumBlocks; assembler;
> FastMM4.pas(3556,31) Error: Generating PIC, but reference is not PIC-safe
> FastMM4.pas(3558,36) Error: Generating PIC, but reference is not PIC-safe

I propose to simplify the procedure to:

```
procedure AcquireSpinLockMediumBlocks;
begin
 AcquireSpinLockByte(MediumBlocksLocked);
end;   
```

this generally solves the problem.

**Pull request closed without merging**
